server:
  port: 8081
#  servlet:
#    context-path: /ewbfs
spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.SQLServer2012Dialect
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false

  datasource:
    #    username: sa
    #    password: P@ss@12345
    #    url: jdbc:sqlserver://10.1.12.110:1433;instanceName=EBSQLSRV;databaseName=EWBFS
    username: root
    password:
    url: jdbc:mysql://localhost:3306/EWBFS
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.1.22.72:8081/auth/realms/enat
#          issuer-uri: http://10.1.12.70:8081/auth/realms/enat

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://10.1.22.72:8761/eureka}
  instance:
    preferIpAddress: true

services:
  hr: 'http://10.1.22.72:8083/hr'
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

